version: "3"

services:
  air-quality-bridge:
    image: ghcr.io/stefanthoss/air-quality-bridge:latest
    container_name: air-quality-bridge
    restart: unless-stopped
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    environment:
      - INFLUXDB_V2_URL=https://localhost:8086
      - INFLUXDB_V2_TOKEN=my-token
      - INFLUXDB_V2_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
      - INFLUXDB_MEASUREMENT=air_quality
      - MQTT_CLIENT_ID=air-quality-bridge
      - MQTT_BROKER_URL=my-mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=air-quality
      - MQTT_PASSWORD=my-password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/info"]
