version: "3"

services:
  air-quality-influxdb-bridge:
    image: air-quality-influxdb-bridge:devel
    ports:
      - 5000:5000
    environment:
      # - FLASK_APP=/app/main.py
      - FLASK_ENV=development
      - APP_SETTINGS=prod.cfg
    volumes:
      - ./prod.cfg:/app/prod.cfg
