name: Python formatting & linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black~=19.10b0 flake8~=3.8.3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Format with black
        run: |
          black --line-length 120 --target-version py38 --check ./
      - name: Lint with flake8
        run: |
          flake8 --select B,C,E,F,W,T4,B9 --ignore E203,E266,E501,W503 --max-line-length 120 --count --show-source --statistics ./
