name: Lint Code Base

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_BLACK_CONFIG_FILE: tox.ini
          VALIDATE_DOCKERFILE: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_YAML: true
